language: python

python:
  - "3.6"
  - "3.7"

os: linux
sudo: required

before_install:
  - sudo apt update -y
  - sudo apt upgrade
  - sudo adduser travis www-data
  - sudo apt install -y python3-pip
  - groups

env:
  matrix:
    - dist: bionic
      mode: developer
    - dist: bionic
      mode: contributor
    - dist: bionic
      mode: prod
    - dist: xenial
      mode: developer
    - dist: xenial
      mode: contributor
    - dist: xenial
      mode: prod

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip3 install -U setuptools
  - pip3 install -e .

# command to run tests, e.g. python setup.py test
script:
  - if [[ $mode == 'developer' ]]; then python setup.py test -s tests.PackagesTests.test_developer_mode; fi;
  - if [[ $mode == 'contributor' ]]; then python setup.py test -s tests.PackagesTests.test_contributor_mode; fi;
  - if [[ $mode == 'prod' ]]; then python setup.py test -s tests.PackagesTests.test_prod_mode; fi;
