dist: bionic
language: python

python:
  - "3.7"

os: linux
sudo: required

before_install:
  - sudo apt update -y
  - sudo apt upgrade -y

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # - pip3 install -U setuptools
  - pip3 install -e .
  - pip3 install docker==1.38
  - pip3 install atelier

# command to run tests, e.g. python setup.py test
script:
  - bash prep.sh
  - inv test bd
