language: python

python:
  - "3.6"
  - "3.7"

os: linux
sudo: required

before_install:
  - sudo apt-get purge mysql* -y
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo apt update -y
  - sudo apt upgrade -y
  - sudo adduser travis www-data
  - sudo apt install -y python3-pip
  - groups

env:
  matrix:
    - dist: bionic
      case: 01
    - dist: bionic
      case: 02
    - dist: bionic
      case: 03
    - dist: xenial
      case: 01
    - dist: xenial
      case: 02
    - dist: xenial
      case: 03

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip3 install -U setuptools
  - pip3 install -e .

# command to run tests, e.g. python setup.py test
script:
  - python setup.py test
