language: python

python:
  - "3.6"

env:
  matrix:
    - dist: trusty
    - dist: xenial

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo apt-get -y install docker-ce
  - pip install -U setuptools
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - inv prep test
