language: python

python:
  - "3.6"
  - "3.7"

env:
  matrix:
    - dist: bionic
      mode: developer
    - dist: bionic
      mode: contributor
    - dist: bionic
      mode: prod
    - dist: xenial
      mode: developer
    - dist: xenial
      mode: contributor
    - dist: xenial
      mode: prod

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - if [[ $mode == 'developer' ]]; then inv prep test.DockerTests.test_developer_mode; fi;
